export default {
  "login": "Tim-mune",
  "id": 76131609,
  "node_id": "MDQ6VXNlcjc2MTMxNjA5",
  "avatar_url": "https://avatars.githubusercontent.com/u/76131609?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Tim-mune",
  "html_url": "https://github.com/Tim-mune",
  "followers_url": "https://api.github.com/users/Tim-mune/followers",
  "following_url": "https://api.github.com/users/Tim-mune/following{/other_user}",
  "gists_url": "https://api.github.com/users/Tim-mune/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Tim-mune/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Tim-mune/subscriptions",
  "organizations_url": "https://api.github.com/users/Tim-mune/orgs",
  "repos_url": "https://api.github.com/users/Tim-mune/repos",
  "events_url": "https://api.github.com/users/Tim-mune/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Tim-mune/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Tim ",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Junior computer scientist",
  "twitter_username": "TimoNesh3",
  "public_repos": 5,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2020-12-16T21:21:16Z",
  "updated_at": "2022-09-28T02:29:11Z"
}